### ISSUE TITLE
Have you trained any dataset on this model? If yes how much WER you have got? 

### ISSUE THREAD

**Issue by usamaehsan** [iankur/ContextNet#1]

**Comment by iankur** [comment]
Hi @usamaehsan,
I have not run any full training yet but hope to do so soon. I will update README and this thread once I have the numbers.

**Comment by iankur** [comment]
Hi @usamaehsan,
I have added WERs for the default setup, you can check README for details. I will close this thread, please feel free to follow up in case of any issue.
